[licenses]
allow = ["MIT", "Apache-2.0", "ISC", "BSD-2-Clause", "BSD-3-Clause", "Zlib"]
confidence-threshold = 0.8

[bans]
multiple-versions = "allow"

audits = { ignore = [] }

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[advisories]
ignore = []
